import type { Metadata } from 'next'
import './globals.css'
import React from 'react'
import Providers from './providers'
import { Header } from '@/components/layout/Header';
import { Footer } from '@/components/layout/Footer';
import { ToastContainer } from 'react-toastify';

export const metadata: Metadata = {
  title: 'journal.sol',
  description: 'Generated by create-solana-dapp',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased dark`}>
        <Providers>
          <div className="min-h-screen bg-background">
            <Header />
            {children}
            <Footer />
            <ToastContainer theme='dark'/>
          </div>
        </Providers>
      </body>
    </html>
  )
}